name: Database Lint

on:
  pull_request_target:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - id: nodeversion
        run: echo "NODE=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: restore Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: install
        run: |
          yarn
      - name: lint
        run: |
          yarn lint
      - name: create-json secret
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: ${{ secrets.GDOC_KEY }}
      - name: Test generation
        run: |
          node src/generate.js test
